package com.jucasoliveira.kitchensink.catalog.adapter.persistence.mongo;

import java.util.List;
import java.util.Map;
import java.util.Set;
import java.util.function.Function;
import java.util.stream.Collectors;

import com.jucasoliveira.kitchensink.TestcontainersConfiguration;
import com.jucasoliveira.kitchensink.catalog.LegacyCatalogSeed;
import org.bson.Document;
import org.junit.jupiter.api.BeforeAll;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Tag;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.context.annotation.Import;
import org.springframework.data.mongodb.core.MongoTemplate;
import org.springframework.data.mongodb.core.query.Criteria;
import org.springframework.data.mongodb.core.query.Query;

import static org.assertj.core.api.Assertions.assertThat;

/**
 * Issue 2.1 — the right-hand side of "same category/product/item counts per locale as the legacy
 * seed; one command reloads".
 *
 * <p>Legacy anchor: {@code PopulateServlet.java:158-162} — with {@code forcefully=true} the servlet
 * drops, recreates and refills the six catalog tables from {@code Populate-UTF8.xml}. Here the
 * property {@code kitchensink.seed.catalog=true} turns on {@link CatalogSeeder}, which drops the
 * three catalog collections and inserts {@code seed/catalog.json} on startup.
 *
 * <p>Every expected figure comes from {@link LegacyCatalogSeed}, which reads a verbatim copy of the
 * legacy XML from the test classpath — never a literal. {@code LegacyCatalogSeedCharacterizationTest} pins
 * what that reader returns; this test pins that the store holds the same after the seeder ran.
 * The fixture in between is generated by {@code scripts/extract-catalog-seed.py}, so a fixture
 * that drifted from the legacy file (hand edit, stale re-run) fails here, not in a demo.
 *
 * <p>Tagged {@code parity}: a red run means the migrated seed no longer matches Pet Store's.
 * The seeder itself is exercised only by this test, so a broken loader also surfaces as a
 * parity failure rather than a build failure — accepted, because the loader has no behaviour
 * other than "match the legacy seed".
 *
 * <p>The extra property makes this a fourth Spring context (and a fourth container) in the
 * suite; see {@code docs/05-test-harness.md} §1 on why that is not worth collapsing.
 */
@Tag("parity")
@SpringBootTest(properties = "kitchensink.seed.catalog=true")
@Import(TestcontainersConfiguration.class)
class CatalogSeedLoadTest {

	static final String CATEGORIES = "categories";
	static final String PRODUCTS = "products";
	static final String ITEMS = "items";
	static final Set<String> LOCALES = Set.of("en_US", "ja_JP", "zh_CN");

	static LegacyCatalogSeed legacy;

	@Autowired
	MongoTemplate mongo;

	@Autowired
	CatalogSeeder seeder;

	@BeforeAll
	static void readTheLegacySeed() {
		legacy = LegacyCatalogSeed.read();
	}

	@Test
	@DisplayName("PopulateServlet.java:158-162 — on startup with the flag on, the store holds the legacy counts: 5 / 16 / 28")
	void the_seeder_ran_at_startup() {
		assertThat(mongo.getCollection(CATEGORIES).countDocuments()).isEqualTo(legacy.categories.size());
		assertThat(mongo.getCollection(PRODUCTS).countDocuments()).isEqualTo(legacy.products.size());
		assertThat(mongo.getCollection(ITEMS).countDocuments()).isEqualTo(legacy.items.size());
	}

	@Test
	@DisplayName("forcefully=true — reloading is drop-then-insert, so a second run leaves the same 49 documents, not 98")
	void reload_is_idempotent() throws Exception {
		seeder.run(null);
		seeder.run(null);
		assertThat(mongo.getCollection(CATEGORIES).countDocuments()).isEqualTo(legacy.categories.size());
		assertThat(mongo.getCollection(PRODUCTS).countDocuments()).isEqualTo(legacy.products.size());
		assertThat(mongo.getCollection(ITEMS).countDocuments()).isEqualTo(legacy.items.size());
	}

	@Test
	@DisplayName("category / product / item primary keys — the same ids, as _id, and nothing else")
	void the_same_ids() {
		assertThat(ids(CATEGORIES)).containsExactlyInAnyOrderElementsOf(
				legacy.categories.stream().map(LegacyCatalogSeed.Category::id).toList());
		assertThat(ids(PRODUCTS)).containsExactlyInAnyOrderElementsOf(
				legacy.products.stream().map(LegacyCatalogSeed.Product::id).toList());
		assertThat(ids(ITEMS)).containsExactlyInAnyOrderElementsOf(
				legacy.items.stream().map(LegacyCatalogSeed.Item::id).toList());
	}

	@Test
	@DisplayName("category_details / product_details / item_details — one embedded row per locale, same count per locale as the legacy tables")
	void the_same_rows_per_locale() {
		for (String locale : LOCALES) {
			assertThat(withLocale(CATEGORIES, locale)).as("category_details rows for %s", locale)
					.isEqualTo(rowsFor(legacy.categories, LegacyCatalogSeed.Category::details, locale));
			assertThat(withLocale(PRODUCTS, locale)).as("product_details rows for %s", locale)
					.isEqualTo(rowsFor(legacy.products, LegacyCatalogSeed.Product::details, locale));
			assertThat(withLocale(ITEMS, locale)).as("item_details rows for %s", locale)
					.isEqualTo(rowsFor(legacy.items, LegacyCatalogSeed.Item::details, locale));
		}
	}

	@Test
	@DisplayName("Populate-UTF8.xml:882 — EST-15 has no ja_JP row in the legacy seed, and the loader fills no gaps")
	void the_gap_is_preserved() {
		Document est15 = mongo.findById("EST-15", Document.class, ITEMS);
		assertThat(est15).isNotNull();
		assertThat(est15.get("details", Document.class).keySet()).containsExactlyInAnyOrder("en_US", "zh_CN");
	}

	@Test
	@DisplayName("XMLDBHandler.java:179-180 — locale keys are the underscore form the DAO queried with")
	void locale_keys_use_the_underscore_form() {
		Set<String> seen = List.of(CATEGORIES, PRODUCTS, ITEMS).stream()
				.flatMap(c -> mongo.findAll(Document.class, c).stream())
				.flatMap(d -> d.get("details", Document.class).keySet().stream())
				.collect(Collectors.toSet());
		assertThat(seen).isEqualTo(LOCALES);
	}

	@Test
	@DisplayName("Product.dtd / Item.dtd — every product's categoryId and every item's productId resolves")
	void references_resolve() {
		Set<String> categoryIds = Set.copyOf(ids(CATEGORIES));
		Set<String> productIds = Set.copyOf(ids(PRODUCTS));
		assertThat(mongo.findAll(Document.class, PRODUCTS)).extracting(d -> d.getString("categoryId"))
				.allMatch(categoryIds::contains);
		assertThat(mongo.findAll(Document.class, ITEMS)).extracting(d -> d.getString("productId"))
				.allMatch(productIds::contains);
	}

	@Test
	@DisplayName("item_details.listprice — EST-1 keeps 16.50 / 1951 / 142 per locale, untouched by the transform")
	void values_survive_the_transform() {
		Document est1 = mongo.findById("EST-1", Document.class, ITEMS);
		LegacyCatalogSeed.Item expected = legacy.items.stream().filter(i -> i.id().equals("EST-1")).findFirst()
				.orElseThrow();
		for (String locale : LOCALES) {
			Document row = est1.get("details", Document.class).get(locale, Document.class);
			assertThat(row.getString("listPrice")).isEqualTo(expected.details().get(locale).listPrice());
			assertThat(row.getString("unitCost")).isEqualTo(expected.details().get(locale).unitCost());
			assertThat(row.getList("attributes", String.class)).isEqualTo(expected.details().get(locale).attributes());
		}
	}

	private List<String> ids(String collection) {
		return mongo.findAll(Document.class, collection).stream().map(d -> d.getString("_id")).toList();
	}

	private long withLocale(String collection, String locale) {
		return mongo.count(Query.query(Criteria.where("details." + locale).exists(true)), collection);
	}

	private static <T> long rowsFor(List<T> entities, Function<T, Map<String, ?>> details, String locale) {
		return entities.stream().filter(e -> details.apply(e).containsKey(locale)).count();
	}

}
